<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="com" nsURI="com" nsPrefix="com">
  <eSubpackages name="fr" nsURI="fr" nsPrefix="fr">
    <eSubpackages name="test" nsURI="test" nsPrefix="test">
      <eSubpackages name="obeonetwork" nsURI="obeonetwork" nsPrefix="obeonetwork">
        <eSubpackages name="eclipse" nsURI="eclipse" nsPrefix="eclipse">
          <eClassifiers xsi:type="ecore:EClass" name="IEditor" abstract="true" interface="true"/>
          <eSubpackages name="impl" nsURI="impl" nsPrefix="impl">
            <eClassifiers xsi:type="ecore:EClass" name="Editor" eSuperTypes="#//fr/test/obeonetwork/eclipse/IEditor">
              <eStructuralFeatures xsi:type="ecore:EReference" name="edit" eType="ecore:EClass edit.ecore#//IEdit"/>
            </eClassifiers>
          </eSubpackages>
        </eSubpackages>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
