<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="org" nsURI="org" nsPrefix="org">
  <eSubpackages name="obeonetwork" nsURI="obeonetwork" nsPrefix="obeonetwork">
    <eSubpackages name="dsl" nsURI="dsl" nsPrefix="dsl">
      <eSubpackages name="demo" nsURI="demo" nsPrefix="demo">
        <eSubpackages name="project1" nsURI="project1" nsPrefix="project1">
          <eSubpackages name="truc" nsURI="truc" nsPrefix="truc">
            <eClassifiers xsi:type="ecore:EClass" name="Interface1" abstract="true"
                interface="true"/>
            <eSubpackages name="bidule" nsURI="bidule" nsPrefix="bidule">
              <eClassifiers xsi:type="ecore:EClass" name="Implem1" eSuperTypes="#//obeonetwork/dsl/demo/project1/truc/Interface1"/>
            </eSubpackages>
          </eSubpackages>
        </eSubpackages>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
